// <auto-generated />
namespace SORANO.WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedVisitsAndVisitors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager("SORANO.WEB.Migrations.201809181753370_AddedVisitsAndVisitors", typeof(AddedVisitsAndVisitors).Assembly);
        
        string IMigrationMetadata.Id
        {
            get { return "201809181753370_AddedVisitsAndVisitors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
