// <auto-generated />
namespace SORANO.WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ExtendArticleAndArticleTypeDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager("SORANO.WEB.Migrations.202102012039370_ExtendArticleAndArticleTypeDescription", typeof(ExtendArticleAndArticleTypeDescription).Assembly);
        
        string IMigrationMetadata.Id
        {
            get { return "202102012039370_ExtendArticleAndArticleTypeDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
