//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SORANO.BLL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SORANO.BLL.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Артикул не может быть удалён..
        /// </summary>
        internal static string ArticleCannotBeDeletedMessage {
            get {
                return ResourceManager.GetString("ArticleCannotBeDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Артикул не найден..
        /// </summary>
        internal static string ArticleNotFoundMessage {
            get {
                return ResourceManager.GetString("ArticleNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип артикулов не может быть удалён..
        /// </summary>
        internal static string ArticleTypeCannotBeDeletedMessage {
            get {
                return ResourceManager.GetString("ArticleTypeCannotBeDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип артикулов не найден..
        /// </summary>
        internal static string ArticleTypeNotFoundMessage {
            get {
                return ResourceManager.GetString("ArticleTypeNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип вложений не может быть удалён..
        /// </summary>
        internal static string AttachmentTypeCannotBeDeletedMessage {
            get {
                return ResourceManager.GetString("AttachmentTypeCannotBeDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип вложений не найден..
        /// </summary>
        internal static string AttachmentTypeNotFoundMessage {
            get {
                return ResourceManager.GetString("AttachmentTypeNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент не может быть удалён..
        /// </summary>
        internal static string ClientCannotBeDeletedMessage {
            get {
                return ResourceManager.GetString("ClientCannotBeDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент не найден..
        /// </summary>
        internal static string ClientNotFoundMessage {
            get {
                return ResourceManager.GetString("ClientNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поставка не может быть удалена..
        /// </summary>
        internal static string DeliveryCannotBeDeletedMessage {
            get {
                return ResourceManager.GetString("DeliveryCannotBeDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поставка не найден..
        /// </summary>
        internal static string DeliveryNotFoundMessage {
            get {
                return ResourceManager.GetString("DeliveryNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место не может быть удалено..
        /// </summary>
        internal static string LocationCannotBeDeletedMessage {
            get {
                return ResourceManager.GetString("LocationCannotBeDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место не найдено.
        /// </summary>
        internal static string LocationNotFoundMessage {
            get {
                return ResourceManager.GetString("LocationNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип мест не может быть удалён..
        /// </summary>
        internal static string LocationTypeCannotBeDeletedMessage {
            get {
                return ResourceManager.GetString("LocationTypeCannotBeDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип мест не найден..
        /// </summary>
        internal static string LocationTypeNotFoundMessage {
            get {
                return ResourceManager.GetString("LocationTypeNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поставщик не может быть удалён..
        /// </summary>
        internal static string SupplierCannotBeDeletedMessage {
            get {
                return ResourceManager.GetString("SupplierCannotBeDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поставщик не найден..
        /// </summary>
        internal static string SupplierNotFoundMessage {
            get {
                return ResourceManager.GetString("SupplierNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимое значение идентификатора пользователя..
        /// </summary>
        internal static string UserInvalidIdentifierMessage {
            get {
                return ResourceManager.GetString("UserInvalidIdentifierMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанный пользователь не найден..
        /// </summary>
        internal static string UserNotFoundMessage {
            get {
                return ResourceManager.GetString("UserNotFoundMessage", resourceCulture);
            }
        }
    }
}
