//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SORANO.BLL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SORANO.BLL.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Артикул не может быть удалён..
        /// </summary>
        internal static string ArticleCannotBeDeletedException {
            get {
                return ResourceManager.GetString("ArticleCannotBeDeletedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Артикул не может быть null..
        /// </summary>
        internal static string ArticleCannotBeNullException {
            get {
                return ResourceManager.GetString("ArticleCannotBeNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимое значение идентификатора артикула..
        /// </summary>
        internal static string ArticleInvalidIdentifierException {
            get {
                return ResourceManager.GetString("ArticleInvalidIdentifierException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Артикул не найден..
        /// </summary>
        internal static string ArticleNotFoundException {
            get {
                return ResourceManager.GetString("ArticleNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип артикула не может быть null..
        /// </summary>
        internal static string ArticleTypeCannotBeNullException {
            get {
                return ResourceManager.GetString("ArticleTypeCannotBeNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимое значение идентификатора типа артикула..
        /// </summary>
        internal static string ArticleTypeInvalidIdentifierException {
            get {
                return ResourceManager.GetString("ArticleTypeInvalidIdentifierException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип артикулов не найден..
        /// </summary>
        internal static string ArticleTypeNotFoundException {
            get {
                return ResourceManager.GetString("ArticleTypeNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Артикул с таким штрих-кодом уже существует..
        /// </summary>
        internal static string ArticleWithSameBarcodeException {
            get {
                return ResourceManager.GetString("ArticleWithSameBarcodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанный пользователь не найден..
        /// </summary>
        internal static string UserNotFoundException {
            get {
                return ResourceManager.GetString("UserNotFoundException", resourceCulture);
            }
        }
    }
}
